language: node_js
node_js:
  - "5"
before_install:
  - "sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test"
  - "sudo apt-get update -qq"
  - "sudo apt-get install -qq g++-4.8"
  - "sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++"
  - "export CXX='g++-4.8'"
  - "npm install tibia-maps -g"
script:
  - "./release.sh && tibia-maps --from-data=./data --output-dir=./Automap && tibia-maps --from-maps=./Automap --output-dir=./data && git status && git diff-index --quiet HEAD --"
git:
  depth: 1
branches:
  only:
    - /^.*$/
