language: node_js
before_install:
  - |
    version=8.26
    wget "https://ftp.gnu.org/gnu/coreutils/coreutils-${version}.tar.xz"
    tar xf "coreutils-${version}.tar.xz"
    rm -rf "coreutils-${version}.tar.xz"
    cd "coreutils-${version}"
    ./configure --quiet && make && sudo make install
    cd ..
    rm -rf "coreutils-${version}"
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++-4.8 --force-yes
  - export CXX='g++-4.8'
script:
  - tibia-maps --version
  - tibia-maps --from-data=./data --output-dir=./Automap
  - tibia-maps --from-maps=./Automap --output-dir=./data
  - git status && git diff-index --quiet HEAD --
after_success:
  - $(npm bin)/set-up-ssh --key "${encrypted_a9c94e6c75dd_key}"
      --iv "${encrypted_a9c94e6c75dd_iv}"
      --path-encrypted-key .travis-github-deploy-key.enc
  - $(npm bin)/update-branch --commands 'npm run build'
      --commit-message "Update generated map data @ ${TRAVIS_COMMIT}"
      --directory 'dist'
      --distribution-branch 'gh-pages'
      --source-branch 'master'
git:
  depth: 1
branches:
  only:
    - master
env:
  global:
    secure: "a9o6n8CUlt69IFeZIzAazJfcauGmfy1bLbgIrmh+vB+b16JTUw7jH2wWnmor6TL5nDKrtaSHukyu0ESSvBVypDRe+7zDx97QoB2RyvIFZVsrBiOF322y7PVAbQyWASiUak5xASq3n9Iv3bWI4Ys9Xt9e4b13eUbVoFGFVn1CNdNkPgE76V71WVhpQxyKe8iEpULXjQKmLSsez5oFB2OTnMiCA9131zsUlDRet5iKjI1fK04P4T6LBUIzpVchjKFTNfVoIjTr1YoBmcqJxikTtQKF5RI6LSVWEo74ey65aoTYAgHn5iJ3KjYQW25nrX5/LURwX8etnxs2e9GtlhidGY7ve+bNtUjbd5v/xLpxzqUh8XJ5gwe68eSuaBw40nCNHlELaIMeHemLS9gCfPCn0jokAkD9M+pCUz2rdrYaT5ukTjroHW99g8X6b2tGm+TfyZW0HE2Xj0iaJuqehxvcBNEleI7VQK3y6KoE0Ttl+N5FtGxbIGYSm+v/pmBRE2qaKxFxrAHNLAyNBda+itpwGRqMzEDSH3JHbxlAblSjqyADyZ+Yl4icAwVpkRJrbIoH1EVcyugnLq48jAphYms8cZ6nyzW76cOCuvrRjifqBSWl6ti7DOUwxg4RMkvU0ayTyaupBscGE68ptDADNEz4ybQ8NrimhBB127ioAY3PELE="
