name: 'Disable Lightbearer pack'

on:
  schedule:
    # Run annually at 04:00 UTC on November 16th.
    - cron: '0 4 16 11 *'
  workflow_dispatch:

jobs:
  disable-lightbearer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm install

      - name: Disable pack
        run: |
          node scripts/disable-marker-pack.mjs lightbearer
          git config user.name 'Mathias Bynens'
          git config user.email 'mathias@qiwi.be'
          git commit data -m 'Disable Lightbearer pack' -m 'This patch disables the Lightbearer markers now that the event (which runs from November 11th until November 15th) has come to an end.'
          git push
