name: 'Enable Orcsoberfest Island pack'

on:
  schedule:
    # Orcsoberfest runs from the second Friday until the third Friday
    # of October and March, followed by a weekend of rewards.
    # Run annually at 04:00 UTC on February 1st. (The pack remains
    # active until October, so there’s no need to re-enable it.)
    # See enable-percht*.yml which overrides this in December.
    - cron: '0 4 1 2 *'
  workflow_dispatch:

jobs:
  import-markers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: Install dependencies
        run: npm install

      - name: Enable pack
        run: |
          scripts/enable-pack.sh orcsoberfest
          git config user.name 'Mathias Bynens'
          git config user.email 'mathias@qiwi.be'
          git commit data -m 'Enable Orcsoberfest Island maps' -m 'This patch replaces the Percht Island maps (and their markers) with the Orcsoberfest Island maps (and their markers) in preparation for the upcoming event.'
          git push
